name: Lint checks
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_NAME: volto-leaflet-block
      NAMESPACE: "@adeweb-be"
      GIT_USER: 'duchenean'
      GIT_BRANCH: ${GITHUB_REF##*/}
    steps:
      - name: Pull latest volto-addon-ci docker image
        run: docker pull plone/volto-addon-ci

      # ESlint
      - name: ESlint
        run: docker run -i --rm --name="eslint" -e NAMESPACE="${{env.NAMESPACE}}" -e DEPENDENCIES="" -e GIT_NAME=${{env.GIT_NAME}} -e GIT_USER=${{env.GIT_USER}} -e GIT_BRANCH=${{env.GIT_BRANCH}} plone/volto-addon-ci eslint

      # Stylelint
      - name: Stylelint
        run: docker run -i --rm --name="stylelint" -e NAMESPACE="${{env.NAMESPACE}}" -e DEPENDENCIES="" -e GIT_NAME=${{env.GIT_NAME}} -e GIT_USER=${{env.GIT_USER}} -e GIT_BRANCH=${{env.GIT_BRANCH}} plone/volto-addon-ci stylelint

      # Prettier
      - name: Prettier
        run: docker run -i --rm --name="prettier" -e NAMESPACE="${{env.NAMESPACE}}" -e DEPENDENCIES="" -e GIT_NAME=${{env.GIT_NAME}} -e GIT_USER=${{env.GIT_USER}} -e GIT_BRANCH=${{env.GIT_BRANCH}} plone/volto-addon-ci prettier
